# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "terrywang/archlinux"

  config.vm.provision "shell", inline: <<-SHELL
     pacman --verbose -Sy
     pacman --verbose --noconfirm -Syu
     pacman --verbose --noconfirm -S docker squashfs-tools apparmor go go-tools python-docutils 
     echo "#########################################"
     echo "###Finished Stage 1 & Starting Stage 2###"
     echo "#########################################"
   SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    git clone https://aur.archlinux.org/snapd.git
    cd snapd
    makepkg --noconfirm -si
    echo "#########################################"
    echo "###Finished Stage 2 & Starting Stage 3###"
    echo "#########################################"
  SHELL
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    systemctl enable --now snapd.socket
    systemctl start snapd.socket
    echo "Enabling classic snap support"
    ln -s /var/lib/snapd/snap /snap #To enable classic snap support
    echo "############################################"
    echo "###Finished Stage 3 - Rebooting System...###"
    echo "############################################"
    systemctl reboot
    echo " "
    echo "##############################################################################"
    echo "###You can now install programs through snap using 'snap install <PROGRAM>'###"
    echo "##############################################################################"
  SHELL
end
